const cityReference = {
  'London, England' : { 'cityDesc' : "London is one of the world's most important global cities and has been called the world's most powerful, most desirable, most influential, most visited, most expensive, sustainable, most investment-friendly, and most-popular-for-work city. It exerts a considerable impact upon the arts, commerce, education, entertainment, fashion, finance, healthcare, media, professional services, research and development, tourism and transportation. London ranks 26th out of 300 major cities for economic performance. It is one of the largest financial centres and has either the fifth- or sixth-largest metropolitan area GDP.[note 3] It is the most-visited city as measured by international arrivals and has the busiest city airport system as measured by passenger traffic. It is the leading investment destination, hosting more international retailers than any other city.", 'cityTemp' : 'Cold', 'cityPhoto' : '' },

  'Perth, Australia' : { 'cityDesc' : "Perth contains a number of important public buildings as well as various historic sites. Notable government buildings include Parliament House, Government House, the Supreme Court Buildings and the Perth Mint. The city is served by Fremantle Harbour and Perth Airport. It was a naval base for the Allies during World War II and the Royal Australian Navy's Fleet Base West is located on Garden Island. All five of Western Australia's universities are based in Perth. The city has been ranked among the world's most liveable cities and was classified by the Globalization and World Cities Research Network in 2020 as a Beta global city.", 'cityTemp' : 'Hot', 'cityPhoto' : '' },

  'Dublin, Ireland' : { 'cityDesc' :"There is archaeological debate regarding precisely where Dublin was established by the Gaels in or before the 7th century AD. Later expanded as a Viking settlement, the Kingdom of Dublin, the city became Ireland's principal settlement following the Norman invasion. The city expanded rapidly from the 17th century and was briefly the second largest city in the British Empire after the Acts of Union in 1800. Following the partition of Ireland in 1922, Dublin became the capital of the Irish Free State, later renamed Ireland.", 'cityTemp' : 'Cold', 'cityPhoto' : '' },

 'Cairo, Egypt' : { 'cityDesc' :"Cairo has the oldest and largest film and music industries in the Arab world, as well as the world's second-oldest institution of higher learning, Al-Azhar University. Many international media, businesses, and organizations have regional headquarters in the city; the Arab League has had its headquarters in Cairo for most of its existence. With a population of over 9 million spread over 3,085 square kilometers (1,191 sq mi), Cairo is by far the largest city in Egypt. An additional 9.5 million inhabitants live in close proximity to the city. Cairo, like many other megacities, suffers from high levels of pollution and traffic. The Cairo Metro is one of the only two metro systems in Africa (the other being in Algiers, Algeria), and ranks amongst the fifteen busiest in the world, with over 1 billion annual passenger rides. The economy of Cairo was ranked first in the Middle East in 2005, and 43rd globally on Foreign Policy's 2010 Global Cities Index.", 'cityTemp' : 'Hot', 'cityPhoto' : '' },

  'Hanoi, Vietnam' : { 'cityDesc' :"The city is a settlement along the banks of the Red River. In 257 B.C, under the rule of king An Dương Vương, the citadel of Cổ Loa, nowaday Đông Anh district of Hanoi, was constructed and served as the capital of Âu Lạc. After the fall of Âu Lạc, the city was renamed to Tống Bình and ultimately Đại La. In 1010, emperor Lý Thái Tổ moved the capital to Đại La, renaming it Thăng Long (literally 'Ascending Dragon'). Thăng Long would remain the political and cultural centre of Vietnam until 1802, when the Nguyễn dynasty, the last imperial dynasty of Vietnam, moved the capital to Huế. The city renamed to Hanoi in 1831, and was the capital of French Indochina from 1883 to 1945. On 6 January 1946, the National Assembly of the Democratic Republic of Vietnam designated Hanoi as the capital of the newly-independent country, which would last during the First Indochina War (1946–1954) and the Vietnam War (1955–1975).", 'cityTemp' : 'Hot', 'cityPhoto' : '' },

  'Khabarovsk, Russia' : { 'cityDesc' :"the largest city and the administrative center of Khabarovsk Krai, Russia, located 30 kilometers (19 mi) from the Chinese border, at the confluence of the Amur and Ussuri Rivers, about 800 kilometers (500 mi) north of Vladivostok. The city was the administrative center of the Far Eastern Federal District of Russia from 2002 until December 2018, when Vladivostok took over that role. It is the largest city in the Russian Far East, having overtaken Vladivostok in 2015. As of the 2010 Census, its population was 577,441. It was previously known as Khabarovka (until 1893).", 'cityTemp' : 'Cold', 'cityPhoto' : '' },

  'Nuuk, Greenland' : { 'cityDesc' :"The city was founded in 1728 by the Dano-Norwegian governor Claus Paarss when he relocated Hans Egede's earlier Hope Colony (Haabets Koloni) to the mainland, and was named Godthåb ('Good Hope'). The city officially adopted its current name in 1979, although the name 'Godthab' remained[when?] in use in Danish. 'Nuuk' is the Greenlandic word for 'cape' (Danish: næs). It is so named because of its position at the end of the Nuup Kangerlua fjord on the eastern shore of the Labrador Sea. Its latitude, at 64°11' N, makes it the world's northernmost capital, only a few kilometres farther north than the Icelandic capital Reykjavík.", 'cityTemp' : 'Cold', 'cityPhoto' : '' },

  'Male, Maldives' : { 'cityDesc' :"Traditionally it was the King's Island, from where the ancient royal dynasties ruled and where the palace was located. The city was then called Mahal.[6] Formerly it was a walled city surrounded by fortifications and gates (doroshi). The Royal Palace (Gan'duvaru) was destroyed along with the picturesque forts (koshi) and bastions (buruzu) when the city was remodelled under President Ibrahim Nasir's rule in the aftermath of the abolition of the monarchy in 1968. However, the Malé Friday Mosque remains. In recent years, the island has been considerably expanded through land-filling operations. Over the years, Malé has been the center of political protests and milestone events.", 'cityTemp' : 'Hot', 'cityPhoto' : '' },

  'Mumbai, India' : { 'cityDesc' :"The seven islands that constitute Mumbai were originally home to communities of Marathi language speaking Koli people. For centuries, the islands were under the control of successive indigenous empires before being ceded to the Portuguese Empire and subsequently to the East India Company when in 1661 Charles II of England married Catherine of Braganza and as part of her dowry Charles received the ports of Tangier and Seven Islands of Bombay. During the mid-18th century, Bombay was reshaped by the Hornby Vellard project, which undertook reclamation of the area between the seven islands from the sea. Along with construction of major roads and railways, the reclamation project, completed in 1845, transformed Bombay into a major seaport on the Arabian Sea. Bombay in the 19th century was characterised by economic and educational development.", 'cityTemp' : 'Hot', 'cityPhoto' : '' }
}

export default cityReference
